[platformio]

[env]
build_flags = -std=c++17
build_unflags =
	-std=c++11
	-std=c++14
	-std=c++20
	-std=c++24
lib_extra_dirs = ../../..

[env:native]
platform = native
debug_build_flags = -O0 -ggdb3 -g3

[env:nano]
board = nanoatmega328
platform = atmelavr
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
